### ISSUE TITLE
图片和章节等链接需要找出一种合适的链接方式

### ISSUE THREAD

**Issue by Arondight** [slackwarecn/slackbook_cn#12]
当前有的未做，有的使用了gitbok 的url，似乎都不是很好。需要确定gitbook 中使用做跳转链接的可行方法。

更多参见 #8 。

**Comment by unnamed42** [comment]
图片直接引用[原网站](http://slackbook.org/beta/)的不行吗？就像

``` markdown
![ ](http://slackbook.org/beta/png/setup-program.png)
```

这样

**Comment by Arondight** [comment]
这个因为还会出离线版本，例如使用gitbook 编译出pdf 等格式，这样的引用会导致图片丢失
