### ISSUE TITLE
前言的那一堆文字该怎么翻译啊

### ISSUE THREAD

**Issue by unnamed42** [slackwarecn/slackbook_cn#34]
[这里](https://raw.githubusercontent.com/slackwarecn/slackbook_cn/master/preface/Conventions_Used_in_this_Book.md)和[这里](https://raw.githubusercontent.com/slackwarecn/slackbook_cn/master/preface/Acknowledgements.md)，那两大堆字体测试文字……
要不我们自己创作点内容放进去？

**Comment by Arondight** [comment]
要不然加个“译者注”吧

> 译者注：该部分在原书中尚未完成

因为Slackbook 3.0 只出到beta，那些人就罢工了。

我觉得按照原书的进度翻译就好，然后建立分支`slackbook_3.0`，之后愿意的话可以在master分支继续发挥。
