### ISSUE TITLE
我感觉 commit 历史有点混乱

### ISSUE THREAD

**Issue by zhustec** [slackwarecn/slackbook_cn#44]
经常出现重复内容的提交，比如 同步上游，Pull #number 这种提交。
我有点好奇大叔是怎么合并 pr 的？
我觉得趁现在 collaborators 少可以 rebase 一下，尽量让 commit 树线性化，只是不要出现太复杂的分叉。
而且最好说明同一章的翻译发 pr 之前用 rebase 把 commit 压缩成一个再发，避免出现 945c4ef8 到 d158a72e 这十来个提交。

**Comment by cantaosir** [comment]
刚在翻chapter_13 Emacs 发现已经有提交了,GIT 不太熟,要不弄个Q群或者其他的什么协调下?

**Comment by Arondight** [comment]
Hi all
1. @farkasity  我觉得commit 历史并不重要……历史的作用就是能够回退到某个时间点，分叉到没太大所谓。开始也是很喜欢简介的历史，然而在上一个公司工作了半年觉得这个好像没多大关系……
2. @cantaosir 在翻译工作开始之前，需要提一个issue，我会在第一时间ref 到 #2 ，这样大家就会知道，这一章已经有人接手了。13 章最先接到的issue 是 #41 ，因此认为在此之前无人接手第13 章，并被 @zhuduiyou 接手。

**Comment by Arondight** [comment]
@farkasity 另外合并PR，我是本地用指令合并的，因为想要本地编译一遍看看是否会有warning。如果本地没有编译环境的话我会用web 的merge 按钮合并
1. checkout -b
2. pull
3. checkout master
4. merge
5. push

**Comment by cantaosir** [comment]
@Arondight 校对的工作最后做吗? 我整本看下来,发现一些小问题,比如错别字.

**Comment by Arondight** [comment]
这个还没开始～

**Comment by Arondight** [comment]
麻烦你发现错误就立刻纠正一下吧，这个很容易忘了，再者又不是每次都能发现

**Comment by Arondight** [comment]
@cantaosir 另外务必查看 #45 中的跟帖

**Comment by cantaosir** [comment]
收到.
