### ISSUE TITLE
翻译第14章,网络

### ISSUE THREAD

**Issue by cantaosir** [slackwarecn/slackbook_cn#45]

**Comment by Arondight** [comment]
ref #2

**Comment by Arondight** [comment]
由于提交 c75615bb9b03d170c4d19b5fe4756760893b9ab6 的影响，请事先同步一下上游。

因为这个提交和此issue 时间过于相近，有冲突的可能，我只在 #43 中留了c17 的patch，其余的都推上去了……

**Comment by Arondight** [comment]
问下楼主日后有意向继续翻译完[这一节](http://slackbook.org/beta/#network_automatic-configuration)吗？

**Comment by cantaosir** [comment]
要赶工了? 准备是这一周内完工,

**Comment by cantaosir** [comment]
PS: github 不太熟悉,都是直接在网站上更新,是不是造成麻烦了?

**Comment by cantaosir** [comment]
你们都是极速啊! TAT

**Comment by nnnewb** [comment]
进度里面看起来快翻完了的样子😹
在2016年03月15日 13:20，cantaosir 写道:

你们都是极速啊!

**Comment by cantaosir** [comment]
已更新
