### ISSUE TITLE
addswap 已经翻译

### ISSUE THREAD

**Issue by zha0300** [slackwarecn/slackbook_cn#6]
###### 注意 请认真的阅读下面的信息
- 你需要一个或多个分区来安装linux,而且我们推荐你还需要创建一个swap分区.
  你需要更多的信息的吧,在终端下 运行setup 来阅读帮助文件
- 假设你遇到了第内存的问题, 你可以尝试在运行setup之前激活swap分区. 当你用cfdisk或cfdisk创建了
  swap 分区后 可以用 
  mkswap /dev/&lt;partition&gt; ; swapon /dev/&lt;partition&gt; 来激活这个分区.
- 当你完成了所有slacklinux分区设置后, 在终端下 输入 setup来运行安装过程.
- 假设你没有彩色的显示器, 请在setup之前输入TERM=vt100.

当你完成这一切之后 你可以用root登陆.

**Comment by Arondight** [comment]
噗233，这个不是PR，这个是Issue 啦～

关于PR 可以看[Collaborating on projects using pull requests ](https://help.github.com/categories/collaborating-on-projects-using-pull-requests)。发PR 的话可以直接从fork 的项目上合并如该项目的分支，主要是比较方便。

我晚上回去先帮你提交一下。

**Comment by Arondight** [comment]
可以装一个[tig](https://github.com/jonas/tig)，这个可以很直观的查看history。

```
$ tig -all
```

Merge 的PR 会显示为不同的线

**Comment by zha0300** [comment]
@@谢啊@@

**Comment by Arondight** [comment]
woc，应该谢谢你才是。

如果以后还会提交的话最好使用PR，这样比较方便，也可以在history 留下你的名字。一些例子可以看[这里](https://github.com/slackwarecn/slackbook_cn/pulls?q=is%3Apr+is%3Aclosed)

**Comment by Arondight** [comment]
抱歉这个机翻的影子实在太多了，稍后我会重新翻译。
