### ISSUE TITLE
 Readme页面中的[获取文档]-[发布页面]点击后内容为空？

### ISSUE THREAD

**Issue by perry2008084** [slackwarecn/slackbook_cn#72]
内容已翻译完成，发布页面要显示的内容要创建?

**Comment by Arondight** [comment]
这个其实还有校对没做，例如错字和不通顺等等。这几天生活遇到大危机，好在现在已经解决了，我想校对完成后再发布离线版本。
另外gitbook 本身就会自动编译出离线版本的。
