### ISSUE TITLE
关于章节间链接

### ISSUE THREAD

**Issue by unnamed42** [slackwarecn/slackbook_cn#8]
有些章节内部插入了到另一部分的链接，这部分我该怎么体现
// 在我翻译的部分都删掉了链接，是纯文字

**Comment by Arondight** [comment]
使用相对路径

**Comment by unnamed42** [comment]
呃……帮忙举个例子吧，我HTML不会
比如官方文档的[这个部分](http://slackbook.org/beta/#boot_dual_partition)有到[另一个部分](http://slackbook.org/beta/#install_part)（在repo里是chapter_02/Partitioning.md）的链接，在网页上的好写，在md文档里的该怎么写？

**Comment by liandesinian** [comment]
[the section called "Partitioning"](../chapter_02/Partitioning.md)

**Comment by liandesinian** [comment]
[the section called “Partitioning”](../chapter_02/Partitioning.md)

**Comment by unnamed42** [comment]
感谢@liandesinian ，已经可以了

**Comment by Arondight** [comment]
我试了一下相对路径似乎是不行的……我记得hexo 好像有类似的毛病，但是有解决方案，我找找看下

**Comment by Arondight** [comment]
warning 类似：

```
warn: page chapter_03/Dual_Booting/Dual_Booting_with_Partitions.md contains an hyperlink to resource outside spine 'xxx' 
```
